apiVersion: v1
kind: Service
metadata:
  name: weaviate-headless
  namespace: weaviate
spec:
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  selector:
    app: weaviate
  type: ClusterIP
  publishNotReadyAddresses: true
  ipFamilies:
    - IPv4
