apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-weaviate
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: weaviate
  project: default
  source:
    path: applications/demo-weaviate
    repoURL: https://github.com/butschi84/kustomization.git
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
